name: Frontend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: sh -c "cd frontend && npm install --legacy-peer-deps"

    - name: Lint
      run: sh -c "cd frontend && npm run lint"

    - name: Test
      run: sh -c "cd frontend && npm test"
